export const PARAM_LABELS = {
  size:       'Size',
  opacity:    'Opacity',
  hardness:   'Hardness',
  softness:   'Softness',
  rotation:   'Rotation',
  thickness:  'Thickness',
  flow:       'Flow',
  strength:   'Strength',
  threshold:  'Threshold',
  sampleSize: 'Sample Size',
  trace:      'Trace',
  mode:       'Mode',
  color:      'Color',
  pickedColor: 'Picked Color',
  x:          'X',
  y:          'Y',
} as const

export const PARAM_TOOLTIPS = {
  size:       'Diameter of the brush tip in pixels',
  opacity:    'Overall transparency of the stroke. Lower values make the stroke more see-through',
  hardness:   'Edge sharpness of the brush tip. 0% = fully feathered and soft, 100% = crisp hard edge',
  softness:   'Adds a secondary feathering layer to the brush shape, independent of hardness',
  rotation:   'Angle of the brush tip shape in degrees (0–359°). Useful with non-circular or thick brushes',
  thickness:  'Squashes the brush tip into an ellipse. 100% = circular, lower values = increasingly flat',
  flow:       'Controls how much paint is applied per dab. At 100 the brush fills quickly; lower values let you build up opacity gradually within a stroke',
  strength:   'How intensely the effect is applied per dab. Higher values produce a stronger result each stroke',
  threshold:  'How different a neighboring pixel\'s color can be from the clicked pixel and still be included in the selection. Higher values select broader color ranges.',
  sampleSize: 'Diameter of the sampling region in pixels. 1 = single pixel, 3 = 3×3 average, etc.',
  trace:      'When on, the clone source follows your cursor at the original offset — lets you paint continuously without resetting the source point',
  satMode:    'Saturate boosts color intensity; Desaturate pulls toward grayscale',
  dodgeMode:  'Lighten pushes pixels toward white; Darken pushes pixels toward black',
  warpMode:   'Warp effect: Push moves pixels along stroke direction, Twirl swirls them, Bloat expands outward, Pucker contracts inward, Reconstruct reverses previous warps',
  brushColor: 'The paint color applied by this brush',
  sampledColor: 'Sampled color (also editable)',
} as const
